### ISSUE TITLE
Full screen message not full screen, self hosted

### ISSUE THREAD

**Issue by lewisnyman** [fightforthefuture/digital-climate-strike#90]
Hello, thanks for making this!

I'm trying to implement the self-hosted option, and the footer message is showing fine. When I set `fullPageDisplayStartDate` to the current day, the text shows correctly but it does not resize to full screen. It looks like widget.js is not receiving the message from the iframe.

My PR is here: https://github.com/ConvivioTeam/Convivio-Site/pull/117
The branch can be previewed here: https://deploy-preview-117--convivio-site.netlify.com/

**Comment by mattlinares** [comment]
Is this a pull request because you have found a fix? I can't see if you've fixed it?

**Comment by mattlinares** [comment]
I made this work by forcing the css on our home page stylesheet with:

```
#DIGITAL_CLIMATE_STRIKE {
	height: 100% !important;
}
```

**Comment by dtoakley** [comment]
Okay great, going to close this issue if that's okay :)

**Comment by mattlinares** [comment]
@dtoakley I'm not sure the issue is resolved.

**Comment by lewisnyman** [comment]
The issue isn't resolved, I'm referencing the PR that contains my implementation where I'm finding the problem. Sorry if that wasn't clear! Here's a screenshot of the problem
![Screenshot 2019-09-19 10 14 18](https://user-images.githubusercontent.com/632390/65230723-48b96480-dac6-11e9-96fa-6e921e19d479.jpg)

**Comment by lewisnyman** [comment]
> I made this work by forcing the css on our home page stylesheet with:
> 
> ```
> #DIGITAL_CLIMATE_STRIKE {
> 	height: 100% !important;
> }
> ```

I don't think I can fix it with this problem this way, as it will apply regardless of date, so the pre-date banner will be 100% height. Is that right?

**Comment by mattlinares** [comment]
@lewisnyman Yes that's true. We are only using it on the day of the strikes, partly due to these problems.

**Comment by lewisnyman** [comment]
After some investigation, I realised that none of the messages are being received from the iframe, so the footer close button, and links, don't work. The problem is on line 144 of widget.js:
`if (event.origin.lastIndexOf(iframeHost, 0) !== 0) return;`

In order to self-host the iframe, I've set:
```
var DIGITAL_CLIMATE_STRIKE_OPTIONS = {
    /**
     * Allow you to override the iFrame hostname. Defaults to https://assets.digitalclimatestrike.net  
     */
    iframeHost: '/climate-strike'
  };
```
Which means `event.origin` is not the same as `iframehost`

**Comment by lewisnyman** [comment]
This is what I had to do to fix the issue for me: https://github.com/ConvivioTeam/Convivio-Site/pull/117/commits/6251f7a92037f552e94a9e9d2145c4f6bb5d634f

**Comment by drumm** [comment]
This was a bit of work for us to sort out to for www.drupal.org. Arrived at a similar solution.

**Comment by drumm** [comment]
https://git.drupalcode.org/project/drupalorg/blob/0edc477f83ed56b0b6d1a30f6e2ef3d1e0e0dd41/drupalorg/digital-climate-strike/widget.js#L22 is what we had to do. A iframePath configuration to go along with iframeHost would be nice.
